version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_DB_URL_HOST=192.168.3.3
      - KC_DB_URL_PORT=5432
      - KC_DB_SCHEMA=public