version: '3'

services:
  postgres:
    image: postgres:alpine3.19
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /mnt/hd/data/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
